config/routes.rb
Rails.application.routes.draw do

  # https://github.com/rails/rails/pull/34477#issuecomment-651467261
  direct :cdn_proxy do |model, options|
    if model.respond_to?(:signed_id)
      route_for(
        :rails_service_blob_proxy,
        model.signed_id,
        model.filename,
        options.merge(host: ENV['ACTIVE_STORAGE_CDN'])
      )
    else
      signed_blob_id = model.blob.signed_id
      variation_key  = model.variation.key
      filename       = model.blob.filename

      route_for(
        :rails_blob_representation_proxy,
        signed_blob_id,
        variation_key,
        filename,
        options.merge(host: ENV['ACTIVE_STORAGE_CDN'])
      )
    end
  end if ENV['ACTIVE_STORAGE_CDN'].present?
  
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  scope "/(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :companies
    resources :tenants
    resources :users

    namespace :quote do
      resources :submissions
    end

    namespace :api, defaults: {format: :json} do
      devise_for :users, :controllers => {sessions: 'api/sessions', registrations: 'api/registrations'}
    end
  end

  get '/:locale' => 'home#index'
end

app/models/tenant.rb
class Tenant < TranslatableRecord
  translateable :name

  validates :name, presence: true
  validates :tenant_key, presence: true
  validates :tenant_key, uniqueness: true

  before_save :parameterize_attributes

  after_create :create_tenant_schema
  after_destroy :drop_tenat_schema

  def self.ensure_bmb_tenant
    bmb_tenant = Tenant.where(tenant_key: 'bmb').first_or_initialize
    if bmb_tenant.new_record?
      bmb_tenant.name = { en: 'Bmb'}
      bmb_tenant.save
    end
    bmb_tenant
  end

  def parameterize_attributes
    self.tenant_key = self.tenant_key.parameterize
  end

  def create_tenant_schema
    Apartment::Tenant.create(self.tenant_key) 
  end

  def drop_tenat_schema
    Apartment::Tenant.drop(self.tenant_key)
  end
end

app/controllers/tenants_controller.rb
class TenantsController < FrontEndController
  before_action :set_tenant, only: [:show, :edit, :update, :destroy]

  # GET /tenants
  # GET /tenants.json
  def index
    @tenants = Tenant.all
  end

  # GET /tenants/1
  # GET /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants
  # POST /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to @tenant, notice: 'Tenant was successfully created.' }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1
  # PATCH/PUT /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to @tenant, notice: 'Tenant was successfully updated.' }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1
  # DELETE /tenants/1.json
  def destroy
    @tenant.destroy
    respond_to do |format|
      format.html { redirect_to tenants_url, notice: 'Tenant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tenant_params
      params.require(:tenant).permit(:tenant_key, :name)
    end
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/tenants/_form.html.erb
<%= form_with(model: tenant, local: true) do |form| %>
  <% if tenant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
        <% tenant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tenant_key %>
    <%= form.text_field :tenant_key %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tenants/edit.html.erb
<h1>Editing Tenant</h1>

<%= render 'form', tenant: @tenant %>

<%= link_to 'Show', @tenant %> |
<%= link_to 'Back', tenants_path %>

app/views/tenants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tenants</h1>

<table>
  <thead>
    <tr>
      
      <th>Key</th>
      <th>Name</th>
      <th colspan='3'></th>
    </tr>
  </thead>

  <tbody>
    <% @tenants.each do |tenant| %>
      <tr>
        <td><%=tenant.tenant_key%></td>
        <td><%=tenant.name%></td>
        <td><%= link_to 'Show', tenant_path(tenant.id) %></td>
        <td><%= link_to 'Edit', edit_tenant_path(tenant) %></td>
        <td><%= link_to 'Destroy', tenant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tenant', new_tenant_path %>

app/views/tenants/new.html.erb
<h1>New Tenant</h1>

<%= render 'form', tenant: @tenant %>

<%= link_to 'Back', tenants_path %>

app/views/tenants/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tenant_path(@tenant) %> |
<%= link_to 'Back', tenants_path %>