config/routes.rb
Rails.application.routes.draw do

  # https://github.com/rails/rails/pull/34477#issuecomment-651467261
  direct :cdn_proxy do |model, options|
    if model.respond_to?(:signed_id)
      route_for(
        :rails_service_blob_proxy,
        model.signed_id,
        model.filename,
        options.merge(host: ENV['ACTIVE_STORAGE_CDN'])
      )
    else
      signed_blob_id = model.blob.signed_id
      variation_key  = model.variation.key
      filename       = model.blob.filename

      route_for(
        :rails_blob_representation_proxy,
        signed_blob_id,
        variation_key,
        filename,
        options.merge(host: ENV['ACTIVE_STORAGE_CDN'])
      )
    end
  end if ENV['ACTIVE_STORAGE_CDN'].present?
  
  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  scope "/(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :companies
    resources :tenants
    resources :users

    namespace :quote do
      resources :submissions
    end

    namespace :api, defaults: {format: :json} do
      devise_for :users, :controllers => {sessions: 'api/sessions', registrations: 'api/registrations'}
    end
  end

  get '/:locale' => 'home#index'
end

app/models/quote.rb
module Quote
  def self.table_name_prefix
    'quote_'
  end
end

app/models/quote/address.rb
class Quote::Address < ApplicationRecord

  include Translateable
  translateable :name

  belongs_to :submission, class_name: 'Quote::Submission'

  validates :name, presence: true
  validates :lat, presence: true
  validates :lon, presence: true
end

app/models/quote/contact.rb
class Quote::Contact < ApplicationRecord
  belongs_to :submission, class_name: 'Quote::Submission'

  validates :name, presence: true
  validates :phone_number, presence: true, if: ->(contact) { contact.email.blank? }
  validates :email, presence: true, if: ->(contact) { contact.phone_number.blank? }
  validates :title, presence: true

  def self.honorific_titles
    I18n.t('common.honorific_titles').map{|key, value| [value, key]}
  end

  def display_contact
    items = []
    items << self.phone_number if self.phone_number
    items << self.email if self.email
    items.join("-")
  end
end

app/models/quote/delivery_address.rb
class Quote::DeliveryAddress < Quote::Address

end

app/models/quote/pickup_address.rb
class Quote::PickupAddress < Quote::Address

end

app/models/quote/shipment_item.rb
class Quote::ShipmentItem < ApplicationRecord
  include Translateable
  translateable :description

  has_one_attached :image
  belongs_to :submission, class_name: 'Quote::Submission', counter_cache: true

  validates :width, presence: true, if: ->(item) { !item.image.attached?}
  validates :length, presence: true, if: ->(item) { !item.image.attached?}
  validates :height, presence: true, if: ->(item) { !item.image.attached?}

  validates :weight, presence: true, if: ->(item) { !item.image.attached?}

  validates :weight_unit, presence: true, if: ->(item) { !item.image.attached?}
  validates :dimension_unit, presence: true, if: ->(item) { !item.image.attached?}

  def self.weight_units
    I18n.t('common.weight_units').map{|key, value| [value, key] }
  end

  def self.dimensional_units
    I18n.t('common.dimensional_units').map{|key, value| [value, key] }
  end

end

app/models/quote/submission.rb
class Quote::Submission < ApplicationRecord

  has_one :pickup_address, class_name: 'Quote::PickupAddress', dependent: :destroy
  has_one :delivery_address, class_name: 'Quote::DeliveryAddress', dependent: :destroy
  has_one :contact, class_name: 'Quote::Contact', dependent: :destroy

  has_many :shipment_items, class_name: 'Quote::ShipmentItem', dependent: :destroy
  enum status: [:open, :assigned, :completed, :confirmed, :closed ]

  accepts_nested_attributes_for :pickup_address, allow_destroy: true
  accepts_nested_attributes_for :delivery_address, allow_destroy: true
  accepts_nested_attributes_for :contact, allow_destroy: true
  accepts_nested_attributes_for :shipment_items, allow_destroy: true
  
end

app/controllers/quote/submissions_controller.rb
class Quote::SubmissionsController < ApplicationController
  before_action :set_quote_submission, only: [:show, :edit, :update, :destroy]

  # GET /quote/submissions
  # GET /quote/submissions.json
  def index
    @quote_submissions = Quote::Submission.includes(:contact, :pickup_address, :delivery_address, :shipment_items).all
  end

  # GET /quote/submissions/1
  # GET /quote/submissions/1.json
  def show
  end

  # GET /quote/submissions/new
  def new
    @quote_submission = Quote::Submission.new
    @quote_submission.build_pickup_address
    @quote_submission.build_delivery_address
    @quote_submission.shipment_items.build
    @quote_submission.build_contact
  end

  # GET /quote/submissions/1/edit
  def edit
  end

  # POST /quote/submissions
  # POST /quote/submissions.json
  def create
    @quote_submission = Quote::Submission.new(quote_submission_params)

    respond_to do |format|
      if @quote_submission.save
        format.html { redirect_to @quote_submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @quote_submission }
      else
        format.html { render :new }
        format.json { render json: @quote_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quote/submissions/1
  # PATCH/PUT /quote/submissions/1.json
  def update
    respond_to do |format|
      if @quote_submission.update(quote_submission_params)
        format.html { redirect_to @quote_submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote_submission }
      else
        format.html { render :edit }
        format.json { render json: @quote_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quote/submissions/1
  # DELETE /quote/submissions/1.json
  def destroy
    @quote_submission.destroy
    respond_to do |format|
      format.html { redirect_to quote_submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote_submission
      @quote_submission = Quote::Submission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_submission_params
      result = params.require(:quote_submission).permit(
            pickup_address_attributes: [:id, :name, :lat, :lon], 
            delivery_address_attributes: [:id, :name, :lat, :lon],
            contact_attributes: [:id, :name, :email, :phone_number, :title],
            shipment_items_attributes: [:id, :width, :length, :height, :weight, :weight_unit, :dimension_unit]
          )
      result
    end
end

app/helpers/quote/submissions_helper.rb
module Quote::SubmissionsHelper
end

app/views/quote/submissions/_form.html.erb
<%= form_with(model: quote_submission, local: true) do |form| %>

  <h2><%=t('models.quote/pickup_address')%></h2>

  <%=form.fields_for :pickup_address do |pickup_form| %>
    <div class="field">
      <%= pickup_form.label :name, t('attributes.pickup_address') %>
      <%= pickup_form.text_field :name, value: quote_submission.pickup_address.name %>
    </div>

    <div>
      <%=pickup_form.hidden_field :id %>
      <%=pickup_form.hidden_field :lat, value: '10' %>
      <%=pickup_form.hidden_field :lon, value: '102' %>
    </div>
  <% end %>

  <h2><%= t('models.quote/delivery_address')%></h2>
  <%=form.fields_for :delivery_address do |delivery_form| %>
    <div class="field">
      <%= delivery_form.label :name, t('attributes.delivery_address') %>
      <%= delivery_form.text_field :name, value: quote_submission.delivery_address.name  %>
    </div>

    <div>
      <%=delivery_form.hidden_field :id %>
      <%=delivery_form.hidden_field :lat, value: '17' %>
      <%=delivery_form.hidden_field :lon, value: '90.39' %>
    </div>
  <% end %>

  <h2><%= t('models.quote/shipment_item')%></h2>

  <%=form.fields_for :shipment_items, quote_submission.shipment_items  do |shipment_item_form| %>
    <%= shipment_item_form.hidden_field :id %>
    <div class="field">
      <%= shipment_item_form.label :width %>
      <%= shipment_item_form.text_field :width %>
    </div>

    <div class="field">
      <%= shipment_item_form.label :length %>
      <%= shipment_item_form.text_field :length %>
    </div>
    
    <div class="field">
      <%= shipment_item_form.label :height %>
      <%= shipment_item_form.text_field :height %>
    </div>

    <div class="field">
      <%= shipment_item_form.label :dimension_unit %>
      <%= shipment_item_form.select :dimension_unit, Quote::ShipmentItem.dimensional_units %>
    </div>

    <div class="field">
      <%= shipment_item_form.label :weight %>
      <%= shipment_item_form.text_field :weight %>
    </div>

    <div class="field">
      <%= shipment_item_form.label :weight_unit %>
      <%= shipment_item_form.select :weight_unit, Quote::ShipmentItem.weight_units %>
    </div>
    
  <% end %>

  <h2><%= t('models.quote/contact')%></h2>
  <%= form.fields_for :contact do |contact_form| %>
    <%= contact_form.hidden_field :id %>
    <div class="field">
      <%= contact_form.label :name %>
      <%= contact_form.text_field :name %>
    </div>

    <div class="field">
      <%= contact_form.label :email %>
      <%= contact_form.text_field :email %>
    </div>

    <div class="field">
      <%= contact_form.label :phone_number %>
      <%= contact_form.text_field :phone_number %>
    </div>

    <div class="field">
      <%= contact_form.label :title %>
      <%= contact_form.select :title, Quote::Contact.honorific_titles %>
    </div>
  <% end %>


  <div class="actions">
    <%= form.submit(t("common.actions.save")) %>
  </div>
<% end %>

app/views/quote/submissions/edit.html.erb
<h1><%= t('models.quote/submission')%></h1>

<%= render 'form', quote_submission: @quote_submission %>

<%= link_to t('common.actions.show'), @quote_submission %> |
<%= link_to t('common.action.back'), quote_submissions_path %>

app/views/quote/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=t("models.quote/submission")%></h1>

<table>
  <thead>
    <tr>
      <th><%= t('attributes.name') %></th>
      <th><%= t('models.quote/contact') %></th>
      <th><%= t('attributes.items_count') %> </th>
      <th><%= t('attributes.pickup_address')%></th>
      <th><%= t('attributes.delivery_address')%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quote_submissions.each do |quote_submission| %>
      <tr>
        <td><%= quote_submission.contact.name%></td>
        <td><%= quote_submission.contact.display_contact%></td>
        <td><%= quote_submission.shipment_items_count%></td>

        <td><%= quote_submission.pickup_address.name%></td>
        <td><%= quote_submission.delivery_address.name%></td>
        <td><%= link_to t('common.actions.show'), quote_submission %></td>
        <td><%= link_to t('common.actions.edit'), edit_quote_submission_path(quote_submission) %></td>
        <td><%= link_to t('common.actions.destroy'), quote_submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('common.actions.new'), new_quote_submission_path %>

app/views/quote/submissions/new.html.erb
<h1><%= t('models.quote/submission')%></h1>

<%= render 'form', quote_submission: @quote_submission %>

<%= link_to t('common.actions.back'), quote_submissions_path %>

app/views/quote/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_quote_submission_path(@quote_submission) %> |
<%= link_to 'Back', quote_submissions_path %>